version: "2"

linters:
  default: standard
  enable:
    - revive
    - gosec
    - bodyclose
    - noctx
    - errorlint
    - contextcheck
    - prealloc
    - unconvert
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
