apiVersion: v1
kind: Service
metadata:
  name: cloudflare-exporter
  labels:
    app.kubernetes.io/name: cloudflare-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9199"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: cloudflare-exporter
  ports:
    - name: metrics
      port: 9199
      targetPort: metrics
