apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-exporter.fullname" . }}-config
  labels:
    {{- include "cloudflare-exporter.labels" . | nindent 4 }}
data:
  {{ .Values.exporter.configPath | base }}: |
    discovery:
      jobs:
        {{- toYaml .Values.exporter.discovery.jobs | nindent 8 }}
    server:
      listenAddress: ":{{ .Values.service.port }}"
      metricsPath: {{ .Values.exporter.metricsPath | quote }}
      scrapeTimeout: {{ .Values.exporter.scrapeTimeout | quote }}
